apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth
spec:
  selector:
    app: auth-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP

